# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 03:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='userlevel',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
