# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 20:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Characters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('cclass', models.CharField(choices=[('FI', 'Fighter'), ('RO', 'Rogue'), ('WI', 'Wizard')], default='FI', max_length=2)),
                ('strength', models.PositiveSmallIntegerField(default=1)),
                ('dexterity', models.PositiveSmallIntegerField(default=1)),
                ('intelligence', models.PositiveSmallIntegerField(default=1)),
                ('health', models.PositiveSmallIntegerField(default=1)),
                ('gold', models.PositiveSmallIntegerField(default=0)),
                ('level', models.PositiveSmallIntegerField(default=1, max_length=3)),
                ('killed_by', models.CharField(default='', max_length=255)),
                ('slug', models.SlugField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Users')),
            ],
        ),
    ]
