# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainmenu', '0002_auto_20170201_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characters',
            name='cclass',
            field=models.CharField(choices=[('FI', 'Fighter'), ('RO', 'Rogue'), ('WI', 'Wizard')], default='FI', max_length=2),
        ),
    ]
