# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 02:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='traps',
            old_name='Tclass',
            new_name='tclass',
        ),
        migrations.RemoveField(
            model_name='treasure',
            name='last_name',
        ),
    ]
