# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='characters',
            name='current_health',
            field=models.SmallIntegerField(default=1),
        ),
    ]
