# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 21:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Treasure',
            new_name='Treasures',
        ),
    ]
