# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 03:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0001_initial'),
        ('mainmenu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='currently_in',
            field=models.ManyToManyField(related_name='populating', to='mainmenu.Characters'),
        ),
        migrations.AddField(
            model_name='rooms',
            name='explored_by',
            field=models.ManyToManyField(related_name='explored', to='mainmenu.Characters'),
        ),
        migrations.AddField(
            model_name='rooms',
            name='monster',
            field=models.ManyToManyField(related_name='denizen', to='game.Monsters'),
        ),
        migrations.AddField(
            model_name='rooms',
            name='trap',
            field=models.ManyToManyField(related_name='dangers', to='game.Traps'),
        ),
        migrations.AddField(
            model_name='rooms',
            name='treasure',
            field=models.ManyToManyField(related_name='reward', to='game.Treasures'),
        ),
        migrations.AddField(
            model_name='items',
            name='owned_by',
            field=models.ManyToManyField(related_name='owner', to='mainmenu.Characters'),
        ),
        migrations.AddField(
            model_name='exits',
            name='comes_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrances', to='game.Rooms'),
        ),
        migrations.AddField(
            model_name='exits',
            name='leads_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exits', to='game.Rooms'),
        ),
    ]
