# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 19:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20170131_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='last_name',
        ),
    ]
