# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainmenu', '0002_auto_20170202_0356'),
        ('game', '0003_auto_20170202_0545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monsters',
            name='alive',
        ),
        migrations.AddField(
            model_name='monsters',
            name='killed_by',
            field=models.ManyToManyField(related_name='killed', to='mainmenu.Characters'),
        ),
    ]
